import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Khushi Ladies Corner",
  description: "Generated by create next app",
};

const bodonimoda = localFont({
  src: [
    {
      path: "../app/fonts/BodoniModa-VariableFont_opsz,wght.ttf",
      weight: "200",
    },
  ],
  variable: "--font-bodonimoda",
});
const prata = localFont({
  src: [
    {
      path: "../app/fonts/Prata-Regular.ttf",
      weight: "200",
    },
  ],
  variable: "--font-prata",
});
const philosopher = localFont({
  src: [
    {
      path: "../app/fonts/Philosopher-Regular.ttf",
      weight: "200",
    },
  ],
  variable: "--font-philosopher",
});
const roboto = localFont({
  src: [
    {
      path: "../app/fonts/Roboto-Regular.ttf",
      weight: "200",
    },
  ],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodonimoda.variable} ${prata.variable} ${philosopher.variable} ${roboto.variable}`}
    >
      <link rel="icon" href="/klc-logo.png" />
      <body>{children}</body>
    </html>
  );
}
